"""make_assigned_to_mandatory

Revision ID: 49073a23c927
Revises: 44e3167d5fb4
Create Date: 2026-05-01 16:35:43.523628

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49073a23c927"
down_revision: Union[str, Sequence[str], None] = "44e3167d5fb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Set assigned_to_id to author_id for existing records where it is currently NULL
    op.execute("UPDATE tickets SET assigned_to_id = author_id WHERE assigned_to_id IS NULL")

    op.alter_column("tickets", "assigned_to_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(op.f("tickets_assigned_to_id_fkey"), "tickets", type_="foreignkey")
    op.create_foreign_key(None, "tickets", "users", ["assigned_to_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tickets", type_="foreignkey")
    op.create_foreign_key(
        op.f("tickets_assigned_to_id_fkey"),
        "tickets",
        "users",
        ["assigned_to_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column("tickets", "assigned_to_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
